config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  get "/logout", to: "sessions#destroy", as: :logout
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :stocks, only: [:index, :new, :create, :show, :edit, :update, :destroy] 
  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    validate :ticker_exists

    def ticker_exists
        #call api to make sure ticker exists
        begin
          @quote = IEX::Resources::Quote.get(ticker)
          stop_is_less_than_price(@quote)


        rescue
            errors.add(:ticker, "is not valid")
        end

    end

    def stop_is_less_than_price(quote)
        #call api to make sure stop is less than price
        if quote.latest_price < stop
            errors.add(:stop, "is more than current price of stock: $#{quote.latest_price}")
        end

    end

    def live_price
        IEX::Resources::Price.get(ticker)
    end

    def stock_logo
        logo = IEX::Resources::Logo.get(ticker)
    end

    def latest_news
        news = IEX::Resources::News.get(ticker,5)
        news.size
        latest = news.first
        latest.headline
        # latest = news.first
        # latest.headline

    end

    def news_url
        news = IEX::Resources::News.get(ticker)
        latest = news.first
        latest.headline
        latest.url
    end


    def dividends_given
        dividends = IEX::Resources::Dividends.get(ticker, '6m')
        if dividends[0] == nil
           return  "This stock doesn't give dividends"
        else
            return dividends[0].amount_dollar
        end
    end

    def dividends_date
        dividends = IEX::Resources::Dividends.get(ticker, '6m')
        if dividends[0] == nil
           return  "This stock doesn't give dividends"
        else
             return dividends[0].payment_date
        end
    end

    def open_price
        ohlc = IEX::Resources::OHLC.get(ticker)
        ohlc.open.price
    end





    def company_name
        company = IEX::Resources::Company.get(ticker)
        company.company_name
    end

    def year_high
        key_stats = IEX::Resources::KeyStats.get(ticker)
        key_stats.week_52_high
    end

    def market_news
    end


end

app/models/user.rb
class User < ApplicationRecord
    has_many :stocks
    has_secure_password
    validates :username, :first_name, :last_name, :email, :phone_number, presence: true

   def eliminate
      @user = User.find_by(params[:username])
      if @user == "Nardeo"
        @user.destroy
      end 
   end

    def self.global_stock_update
        @users = User.all
        @users.each do |user|
            user.stocks.each do |stock|
               @live_price = IEX::Resources::Price.get(stock.ticker)
               if @live_price <= stock.stop
                user.stop_alert(@live_price, stock)
               end

            end

        end
    end

    def stop_alert(live_price, stock)
        p "alerted #{username} of stock stop
        #{stock.ticker} just hit #{live_price} which is under #{stock.stop}"
        account_sid = "ACe89054f9f9aacfdfe4d21134a456f244"
        auth_token = ENV["TWILIO_ACCOUNT_AUTH_TOKEN"]
        @message = "Hey, #{stock.ticker} just hit $#{live_price} which is under $#{stock.stop}"
        @client = Twilio::REST::Client.new(account_sid, auth_token)

        message = @client.messages.create(
        body: @message,
        to: "+1#{phone_number}",
        from: "+19083565998"
        )
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        if session[:user_id] != nil
            redirect_to "/users/"+ session[:user_id].to_s
        end
    end

    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to "/users/"+@user.id.to_s
        else 
            @error = "Email or Password is Incorrect"
            render "new"

        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to new_session_path
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def edit
        @stock = Stock.find(params[:id])
        @stocks = Stock.all
      end
    
    def show
        @stock = Stock.find(params[:id])
      end

    def new
        @stock = Stock.new
    end

    def create
        @stock = Stock.new(stock_params)
        @stock.user_id = params[:user_id]
        if @stock.valid?
          @stock.save
          redirect_to "/users/#{params[:user_id]}/stocks/#{@stock.id}"
          
        else
            @errors = @stock.errors.full_messages
            render 'new'
        end
      end

    def index 
        @stocks = Stock.all
    end
    

      def update 
        @stock = Stock.find(params[:id])
        if @stock.update(stock_params)
          redirect_to "/users/#{params[:user_id]}", notice: "Stock Updated"
        end
      end

      def destroy 
        @stock = Stock.find(params[:id])
        @stock.destroy
        respond_to do |format|
          format.html { redirect_to user_path(@user.id) }
          format.json { head :no_content }
          format.js { render :layout => false }
        end
      end
    

    private 
    def stock_params
        params.require(:stock).permit(:ticker, :stop)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        @stocks = @user.stocks
    end

    def new
        @user = User.new
    end


    def create
        @user = User.new(user_params)
        if @user.valid?
          @user.save
          session[:user_id] = @user.id
          redirect_to "/users/#{@user.id}"
        else

          render 'new'
        end
      end

      def edit
        @user = User.find(params[:id])
        @stocks = Stock.all
      end

      def index
        @users = User.all

      end

      def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to "/users/#{@user.id}", notice: 'Updated'
        end

      end



    def delete
    end

    private
    def user_params
        params.require(:user).permit(:username, :first_name, :last_name, :email, :phone_number, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find(session[:user_id])
    end
    def logged_in?
        !!session[:user_id]
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usesrs_helper.rb
module UsesrsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Old+Standard+TT" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>


    <%= yield %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  </body>
</html>

app/views/stocks/destroy.js.erb
$('.delete_stock').bind('ajax:success', function() {  
        $(this).closest('.wrapper').fadeOut();
     console.log('this worked')
});

app/views/stocks/edit.html.erb
<header>
  <div id="header-container">
    <div id="button-container-right">
      <div id="logout-button">
      <%= link_to "Log Out", logout_path, :class => 'loglink' %>
      </div>
      <div id="button-edit">
        <%= link_to "Profile", user_path(session[:user_id]), :class => "backbutton" %>
      </div>
    </div>
  </div>
</header>

<div id="new-stock-container" class="new-stock-container">
  <div class="big-title-container">
  <div class="new-stock-form-container">
    <h1 class="form-top-title">Edit Stock</h1>
  </div>
  <div class="medium-container">

<%= form_for @stock, url: {action: "update"}, html: {class: "stockform"}, method: :PATCH do |f| %>
    <div class="ticker">
    <%= f.label :ticker%><br>
  <%= f.text_field :ticker %>
  </div>

  <div class="stop">
  <%=f.label :stop%><br>
  <%= f.number_field :stop, step: :any  %>
  </div>



<div class="button">
  <%= f.submit "Update" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/stocks/index.html.erb
<h1>Yerrrrr</h1>

app/views/stocks/new.html.erb
<div class="animated flash sleep-2s", id="error">
<% if @errors %>
<% @errors.each do |error| %>
    <p><%= error %></p>
    <% end %>
<% end %>
</div>

<div id="new-stock-container" class="new-stock-container">
  <div class="big-title-container">
  <div class="new-stock-form-container">
    <h1 class="form-top-title">Choose A Stock</h1>
  </div>
  <div class="medium-container">
<%= form_for @stock, url: {action: "create"}, html: {class: "stockform"} do |f| %>

    <div class="ticker">
    <%= f.label :ticker%><br>
  <%= f.text_field :ticker %>
  </div>

  <div class="stop">
  <%=f.label :stop%><br>
  <%= f.number_field :stop, step: :any %>
  </div>



<div class="button">
  <%= f.submit "add" %>
  </div>
<% end %>
</div>
</div>
</div>
 

app/views/stocks/show.html.erb
<header>
  <div id="header-container">
    <div id="user-title" class="title"><%= @stock.company_name%></div>
    <div id="button-container-right">
      <div id="button-edit">
        <%= link_to "Stock List", user_path(session[:user_id]), :class => 'prof' %>
      </div>
      <div id="button-edit">
      <%= link_to "Add Stock", new_user_stock_path(params[:user_id], params[:id]), :class => 'stocklink'%>
      </div>
    </div>
  </div>
</header>
<div id="name-container" class="name-container">
<div class="company-title"><%= @stock.company_name %> (<%= @stock.ticker %>)</div>
</div>
<%= @stock.market_news %>

<div id="real-time-price" class="real-time-price">
$<%= @stock.live_price %>
</div>

<table class="stocktable", id="stocktable">

  <tbody>
  <tr>
      <td>Open Price</td>
      <td>$<%=@stock.open_price%></td>
    </tr>
    <tr>
      <td>Dividend Date</td>
      <td><%=@stock.dividends_date%></td>
    </tr>
    <tr>
      <td>Dividend Amount</td>
      <td><%=@stock.dividends_given%></td>
    </tr>


    <tr>
      <td>52 Week High</td>
      <td>$<%= @stock.year_high%></td>
    </tr>
  </tbody>
</table>



<div id="news" class="news">
<h2>Latest News</h2>
<a href="<%= @stock.news_url%>"><%= @stock.latest_news %></a>
<div>

app/views/users/edit.html.erb
<div id="new-stock-container" class="new-stock-container">
  <div id="new-stock-container" class="new-stock-container">
    <div class="big-title-container">
    <div class="new-stock-form-container">
      <h1 class="form-top-title">Edit Your Profile</h1>
    </div>
    <div class="medium-container">
<%= form_for @user, method: :PATCH, url: {action: "update"}, html: {class: "userform"} do |f| %>

    <div class="username">
    <%= f.label :username%><br>
  <%= f.text_field :username %>
  </div>

  <div class="firstname">
    <%= f.label :firstname%><br>
  <%= f.text_field :first_name %>
  </div>

  <div class="lastname">
    <%= f.label :lastname%><br>
  <%= f.text_field :last_name %>
  </div>

  <div class="email">
  <%=f.label :email%><br>
  <%= f.text_field :email %>
  </div>
  <div class="phonenumber">
  <%= f.label :phone_number%><br>
  <%= f.text_field :phone_number, :placeholder => "+1" %>
  </div>



<div class="button">
  <%= f.submit "Update" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<h1>This Works</h1>

app/views/users/new.html.erb
<div class="error", id="error">
<% if @errors %>
<% @errors.each do |error| %>
    <p><%= error %></p>
    <% end %>
<% end %>

</div>
<div id="user-form-container" class="user-form-container">
  <div class="title-block">
  <div class="form-container">
    <h1 class="form-title">Sign Up</h1>
    </div>
<%= form_for @user, url: {action: "create"}, html: {class: "userform"} do |f| %>

    <div class="username">
    <%= f.label :username%><br>
  <%= f.text_field :username %>
  </div>

  <div class="firstname">
    <%= f.label :firstname%><br>
  <%= f.text_field :first_name %>
  </div>

  <div class="lastname">
    <%= f.label :lastname%><br>
  <%= f.text_field :last_name %>
  </div>

  <div class="email">
  <%=f.label :email%><br>
  <%= f.text_field :email %>
  </div>
  <div class="phonenumber">
  <%= f.label :phone_number%><br>
  <%= f.text_field :phone_number,:placeholder => "+1" %>
  </div>
  <div class="password">
  <%=f.label :password%><br>
  <%= f.password_field :password %>
  </div>

  <div class="confirmpassword">
  <%=f.label :password_confirmation%><br>
  <%= f.password_field :password_confirmation %>
  </div>


<div class="button">
  <%= f.submit "Join" %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<header>
  <div id="header-container">
    <div id="user-title" class="title"><%= @user.username%></div>
    <div id="button-container-right">
      <div id="logout-button">
      <%= link_to "Log Out", logout_path, :class => 'loglink' %>
      </div>
      <div id="button-edit">
      <%=link_to "Account Settings", edit_user_path(@user.id), :class=> 'editlink' %>
      </div>
    </div>
  </div>
</header>

<table id="table" class="table">
      <tr class="header">
        <th scope="col">Symbol</th>
        <th scope="col">Company</th>
        <th scope="col">Stop Price</th>
        <th scope="col">Live Price</th>
        <th scope="col">Update</th>
        <th scope="col">Remove</th>
      </tr>
<% if @user.stocks %>
  <% @user.stocks.each do |stock| %>
      <tr>
        <td><%= link_to stock.ticker, user_stock_path(@user.id, stock) %></td>

        <td><%= stock.company_name %></td>


        <td>$<%= stock.stop %></td>

        <td>$<%= stock.live_price %></td>

        <td><%=link_to "Edit", edit_user_stock_path(@user.id, stock) %>
        </td>

        <td><%= link_to "Delete", user_stock_path(@user.id, stock), remote: true, method: :delete, :class => 'delete_stock' %></td>
        </tr>
    <% end %>

    <% end %>
    </table>
    <div id="bottom" class="bottom">
  <div id="container-left">
    <div id="stock-button" class="stock-button">
   <%= link_to "Add Stock", new_user_stock_path(@user.id), :class => 'stocklink'%>
   </div>
  </div>
  </div>